packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@shikijs/langs": 4.0.2
  "@shikijs/themes": 4.0.2
  "@tailwindcss/typography": ^0.5.19
  "@tailwindcss/vite": ^4.2.2
  "@types/node": ^24
  elysia: ^1.4.28
  html-to-text: ^9.0.5
  lit: ^3.3.2
  marked: ^17.0.5
  preact: ^10.29.0
  preact-render-to-string: ^6.6.6
  shiki: 4.0.2
  tailwindcss: ^4.2.2
  typedoc: ^0.28.18
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
