packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@types/node": ^24
  preact: ^10.29.0
  preact-render-to-string: ^6.6.6
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
