name: Publish
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies and build
        run: yarn
      - name: Bump version
        run: npm version 0.0.$(git rev-list --count HEAD)-$(date +'%Y%m%d%H%M%S')
      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
